### ISSUE TITLE
[Execution] Logical design of bechmark context and benchmark scenario

### ISSUE THREAD

**Issue by Shu-Wan** [CausalBenchOrg/CausalBench#12]
## Describe the problem
The current `Pipeline` implemented in causalbench package is not equivalent to "**BenchmarkContext**" in the paper.
A **Context** allows multiple data, model, and metrics.

However, current `Pipeline` module only support **one** data, **one** model and multiple metrics (a scenario). 

For example, in a Pipeline config

```yaml
type: pipeline
name: pipeline1
task: discovery.temporal
dataset:
    id: 2
model:
    id: 2
    parameters:
        data: file1
metrics:
    -   id: 5
        parameters:
            ground_truth: file2
    -   id: 6
        parameters:
            ground_truth: file2
```
A user need to specify files (that are from dataset) to models and metrics. Current implementation does not support multiple dataset, as it have more than one files.

Say a user want to create a `Context` with 2 data, 2 model, 2 metric, current workaround is to create 4 `Pipeline`s
```
data1, model1, {met1, met2}
data1, model2, {met1, met2}
data2, model1, {met1, met2}
data2, model2, {met1, met2}
```
However, it's unclear how to _automatically_ specify (input, groundtruth) files to model and metrics.

@AbhinavGor 
1. To create a benchmark context, the user can either upload a config file for a benchmarkContext with > 1 dataset, model, metric. The benchmark scenarios are created logically, but there is no table listing each benchmark scenario for a given context. But because the _causalbench package_  can only generate config with one dataset and one model and multiple metrics, this essentially becomes a _benchmark scenario_.
2. Option 2 to create a benchmark context is through the form, when the user submits the form with _d_ datasets, _m_ models and _a_ metrics, the total number of possible scenarios will be _d * m_, this basically means that we need to create _d * m_ config files for this to work with the package. This can be done but does not make sense to me.
3. Another issue with point 2 is that when the user adds multiple datasets(_D1_ and _D2_), in D1, file 1 can be ground truth and file 2 can be the input data to the model but in D2, it could be the reverse, this again points to a flaw in how the " _benchmark context_" config file is structured.

**EDIT:** We need to come up with a solution fast. In any case, this will need a lot of changes in the backend and the frontend and I am not sure if we will have enough time for this.

@Shu-Wan It's get more complicated when users mix datasets/models/metrics that support different tasks.
